config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  get 'users/:id' => 'users#show'
  root 'pages#index'
  resources :posts
  put '/post/:id/like', to: 'posts#like', as: 'like'
  delete '/post/:id/like', to: 'posts#unlike', as: 'unlike'
  get'/search' => 'posts#search', :as => 'search_page'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :title, presence: true, length: { minimum: 6, maximum:100 }
  validates :description, presence: true, length: { minimum: 10, maximum:300 }

  def liked?(user)
    !!self.likes.find {|like| like.user_id == user.id}
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :new, :create, :search]

  def unlike
    if !(already_liked?)
      flash[:notice] = Cannot unlike
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field") and return
    else
      @parameter = params[:search].downcase
      @results = Post.all.where("lower(title) LIKE :search", search: @parameter)
    end
  end

  def like
    Like.create(user: current_user, post: @post)
    redirect_to post_path(@post)
  end

  def show
  end

  def edit
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Post was successfully deleted"
      redirect_to "/posts"
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post was updated successfully"
      redirect_to "/posts"
    else  
      render 'edit'
    end
  end

  def index
    @post = Post.order(:id)
    if params[:order] == 'title'
      @post = Post.all.order('title')
    elsif params[:order] == 'likes_count'
        @post = Post.all.order('likes_count DESC')
    else
      @post = Post.all
    end
  end

  def new
   @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to "/posts"
      flash[:notice] = "Post was successfully added"
    else
      render 'new'
    end
  end

  private


  def set_post
    @post = Post.find(params[:id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :user_id)
  end

end

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= render "posts/shared/error_messages" %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
  <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"}  %>
<% end %>

app/views/posts/index.html.erb
<h1>Index post page</h1>
<table BORDER>
  <thead>
    <tr> 
      <th>ID</th>
      <th>TITLE</th>
      <th>DESCRIPTION</th>
      <th>USER_ID</th>
      <th>LIKES</th>
      <th>Actions</th>
    </tr>
  </thead>
<% @post.each do |post| %>
  <tbody>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.title %></td>
      <td><%= post.description %></td>
      <td><%= post.user_id %></td>
      <td><%= post.likes.size %></td>
      <td>
        <%= link_to "Show", post_path(post)%>
        <%= link_to "Edit post", edit_post_path(post)%>
        <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: "Are you sure?"}  %>
      </td>
    </tr>
  </tbody>
<% end %>
</table>
<p>Sort by: 
<%= link_to "likes", posts_path(order: 'likes_count') %>
<%= link_to "title", posts_path(order: 'title') %>
</p> 

app/views/posts/new.html.erb
<h1>New post page</h1>

<%= form_for @post do |f| %>
  <%= render "posts/shared/error_messages" %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/posts/search.html.erb
<h1>Search results</h1>
<% @results.each do |result| %>  
  <strong>Title: </strong> <%= result.title %>
  <strong>Description: </strong> <%= result.description %>
  <strong>Likes: </strong> <%= result.likes.size %>  
<% end %>

app/views/posts/show.html.erb
<table BORDER>
  <thead>
    <tr> 
      <th>TITLE</th><th>DESCRIPTION</th><th>USER_ID</th><th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @post.title %></td>
      <td><%= @post.description %></td>
      <td><%= @post.user_id %></td>
      <td>
        <%= link_to "Edit post", edit_post_path(@post)%> 
        <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  </tbody>
</table>
<% if user_signed_in? %>
    <% if @post.liked?(current_user) %>
      <%= button_to "Unlike", like_path(@post), method: "delete" %>
    <% else %>
      <%= button_to "Like", like_path(@post), method: "put" %>
    <% end %>
  <% end %>